services:
  sandbox:
    build:
      context: ../
      dockerfile: ./sandbox/Dockerfile
    environment:
      WEB_URL: ${WEB_URL}
      REPO_URL: ${REPO_URL}
      SANDBOX_SECRET: ${SANDBOX_SECRET}
    network_mode: 'host'
    deploy:
      resources:
        limits:
          cpus: '0.50' # Limit CPU usage to 50%
          memory: 2G
