services:
  web:
    build:
      context: ../
      dockerfile: ./web/Dockerfile
    ports:
      - 3000:3000
      - 7006:7006
    environment:
      ORIGIN: ${ORIGIN}
      SANDBOX_SECRET: ${SANDBOX_SECRET}
      ADMIN_USERNAME: ${ADMIN_USERNAME}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      DATABASE_URL: file:db/data.db
      GIT_PORT: 7006
    volumes:
      - ./repo:/app/web/repo
      - ./db:/app/web/db
    restart: unless-stopped
