services:
  web:
    build:
      context: ../
      dockerfile: ./web/Dockerfile
    ports:
      - 3000:3000
      - 7006:7006
    environment:
      ORIGIN: http://localhost:3000
      WEB_SANDBOX_SECRET: supersecret
      ADMIN_USERNAME: admin
      ADMIN_PASSWORD: bw123
      DATABASE_URL: file:db/data.db
      GIT_PORT: 7006
    volumes:
      - ./repo:/app/web/repo
      - ./db:/app/web/db
    restart: unless-stopped
